# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bars.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nbars.proto\"\xff\x01\n\rSyllableProto\x12\x10\n\x08syllable\x18\x01 \x01(\t\x12\x16\n\tbar_index\x18\x02 \x01(\x05H\x00\x88\x01\x01\x12\x13\n\x06offset\x18\x03 \x01(\x01H\x01\x88\x01\x01\x12\x15\n\x08\x64uration\x18\x04 \x01(\x01H\x02\x88\x01\x01\x12\x12\n\x05pitch\x18\x05 \x01(\x01H\x03\x88\x01\x01\x12$\n\x0bparent_word\x18\x06 \x01(\x0b\x32\n.WordProtoH\x04\x88\x01\x01\x12\x13\n\x06marked\x18\x07 \x01(\x08H\x05\x88\x01\x01\x42\x0c\n\n_bar_indexB\t\n\x07_offsetB\x0b\n\t_durationB\x08\n\x06_pitchB\x0e\n\x0c_parent_wordB\t\n\x07_marked\"T\n\tWordProto\x12\x0c\n\x04word\x18\x01 \x01(\t\x12!\n\tsyllables\x18\x02 \x03(\x0b\x32\x0e.SyllableProto\x12\x0f\n\x02id\x18\x03 \x01(\tH\x00\x88\x01\x01\x42\x05\n\x03_id\"\x9c\x01\n\x08\x42\x61rProto\x12\x19\n\x05words\x18\x01 \x03(\x0b\x32\n.WordProto\x12!\n\tsyllables\x18\x02 \x03(\x0b\x32\x0e.SyllableProto\x12\x16\n\traw_words\x18\x03 \x01(\tH\x00\x88\x01\x01\x12\x1a\n\rraw_syllables\x18\x04 \x01(\tH\x01\x88\x01\x01\x42\x0c\n\n_raw_wordsB\x10\n\x0e_raw_syllables\"`\n\tSongProto\x12\x0e\n\x06\x61rtist\x18\x01 \x01(\t\x12\x0c\n\x04song\x18\x02 \x01(\t\x12\x17\n\x04\x62\x61rs\x18\x03 \x03(\x0b\x32\t.BarProto\x12\x12\n\x05\x61udio\x18\x04 \x01(\x0cH\x00\x88\x01\x01\x42\x08\n\x06_audiob\x06proto3')



_SYLLABLEPROTO = DESCRIPTOR.message_types_by_name['SyllableProto']
_WORDPROTO = DESCRIPTOR.message_types_by_name['WordProto']
_BARPROTO = DESCRIPTOR.message_types_by_name['BarProto']
_SONGPROTO = DESCRIPTOR.message_types_by_name['SongProto']
SyllableProto = _reflection.GeneratedProtocolMessageType('SyllableProto', (_message.Message,), {
  'DESCRIPTOR' : _SYLLABLEPROTO,
  '__module__' : 'bars_pb2'
  # @@protoc_insertion_point(class_scope:SyllableProto)
  })
_sym_db.RegisterMessage(SyllableProto)

WordProto = _reflection.GeneratedProtocolMessageType('WordProto', (_message.Message,), {
  'DESCRIPTOR' : _WORDPROTO,
  '__module__' : 'bars_pb2'
  # @@protoc_insertion_point(class_scope:WordProto)
  })
_sym_db.RegisterMessage(WordProto)

BarProto = _reflection.GeneratedProtocolMessageType('BarProto', (_message.Message,), {
  'DESCRIPTOR' : _BARPROTO,
  '__module__' : 'bars_pb2'
  # @@protoc_insertion_point(class_scope:BarProto)
  })
_sym_db.RegisterMessage(BarProto)

SongProto = _reflection.GeneratedProtocolMessageType('SongProto', (_message.Message,), {
  'DESCRIPTOR' : _SONGPROTO,
  '__module__' : 'bars_pb2'
  # @@protoc_insertion_point(class_scope:SongProto)
  })
_sym_db.RegisterMessage(SongProto)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SYLLABLEPROTO._serialized_start=15
  _SYLLABLEPROTO._serialized_end=270
  _WORDPROTO._serialized_start=272
  _WORDPROTO._serialized_end=356
  _BARPROTO._serialized_start=359
  _BARPROTO._serialized_end=515
  _SONGPROTO._serialized_start=517
  _SONGPROTO._serialized_end=613
# @@protoc_insertion_point(module_scope)
